const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Anchor,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Plugins.NinePatch,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.PlatformInfo,
		C3.Plugins.LocalStorage,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Keyboard,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.PlatformInfo.Cnds.IsWebExport,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Exps.int,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.Browser.Exps.Language,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{bool: 0},
	{Tween: 0},
	{Anchor: 0},
	{btnMore: 0},
	{Sine: 0},
	{GameLogo: 0},
	{TiledBackground: 0},
	{boardLevel: 0},
	{btnPlay: 0},
	{btnFullscreen: 0},
	{btnLanguage: 0},
	{btnSound: 0},
	{tenz: 0},
	{numbers: 0},
	{Over: 0},
	{LoadLogo: 0},
	{bgLoad: 0},
	{loadLine: 0},
	{GameOverBoard: 0},
	{btnOverNext: 0},
	{btnOverHome: 0},
	{TxtGameOver: 0},
	{btnHome: 0},
	{TXTLevel: 0},
	{Block: 0},
	{lastIndex: 0},
	{boardBlocks: 0},
	{Num: 0},
	{BlockLogo: 0},
	{boardBlockLogo: 0},
	{CompleteBlocks: 0},
	{Type: 0},
	{LaterActive: 0},
	{index: 0},
	{Coun: 0},
	{Block2: 0},
	{Elements: 0},
	{numbers2: 0},
	{"9patch": 0},
	{Light: 0},
	{boardLigh: 0},
	{btnShop: 0},
	{numbers3: 0},
	{boardShop: 0},
	{btnBomb: 0},
	{btnClose: 0},
	{btnMolot: 0},
	{btnSpine: 0},
	{Audio: 0},
	{Touch: 0},
	{Browser: 0},
	{PlatformInfo: 0},
	{LocalStorage: 0},
	{AJAX: 0},
	{Array: 0},
	{Keyboard: 0},
	{Pin: 0},
	{COll: 0},
	{Spells: 0},
	{Language: 0},
	{Level: 0},
	{Sound: 0},
	{Collect1: 0},
	{Collect2: 0},
	{Collect3: 0},
	{TopY: 0},
	{LeftX: 0},
	{RightX: 0},
	{Lock: 0},
	{M: 0},
	{StartX: 0},
	{StartY: 0},
	{Y: 0},
	{Action: 0},
	{X: 0},
	{X2: 0},
	{Y2: 0},
	{Index1: 0},
	{Index2: 0},
	{Win: 0},
	{ParseLight: 0},
	{Animation: 0}
];

self.InstanceType = {
	btnMore: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	boardLevel: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	btnFullscreen: class extends self.ISpriteInstance {},
	btnLanguage: class extends self.ISpriteInstance {},
	btnSound: class extends self.ISpriteInstance {},
	numbers: class extends self.ISpriteInstance {},
	Over: class extends self.ISpriteInstance {},
	LoadLogo: class extends self.ISpriteInstance {},
	bgLoad: class extends self.ISpriteInstance {},
	loadLine: class extends self.IWorldInstance {},
	GameOverBoard: class extends self.ISpriteInstance {},
	btnOverNext: class extends self.ISpriteInstance {},
	btnOverHome: class extends self.ISpriteInstance {},
	TxtGameOver: class extends self.ISpriteInstance {},
	btnHome: class extends self.ISpriteInstance {},
	TXTLevel: class extends self.ISpriteInstance {},
	Block: class extends self.ISpriteInstance {},
	boardBlocks: class extends self.ISpriteInstance {},
	BlockLogo: class extends self.ISpriteInstance {},
	boardBlockLogo: class extends self.ISpriteInstance {},
	CompleteBlocks: class extends self.ISpriteInstance {},
	Block2: class extends self.ISpriteInstance {},
	Elements: class extends self.ISpriteInstance {},
	numbers2: class extends self.ISpriteInstance {},
	_9patch: class extends self.IWorldInstance {},
	Light: class extends self.IParticlesInstance {},
	boardLigh: class extends self.ISpriteInstance {},
	btnShop: class extends self.ISpriteInstance {},
	numbers3: class extends self.ISpriteInstance {},
	boardShop: class extends self.ISpriteInstance {},
	btnBomb: class extends self.ISpriteInstance {},
	btnClose: class extends self.ISpriteInstance {},
	btnMolot: class extends self.ISpriteInstance {},
	btnSpine: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Array: class extends self.IArrayInstance {},
	Keyboard: class extends self.IInstance {},
	COll: class extends self.ISpriteInstance {},
	Spells: class extends self.ISpriteInstance {}
}